
# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import pandas as pd
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QFileDialog, QDialog, QMessageBox
from modules import SLMISHandler, TableModel
from authenticationDialog import Ui_Dialog
from selenium.webdriver.common.by import By
import json
import os



FILE_FILTERS = [
 "Excel Files (*.xlsx *.xls)",
]

class Ui_MainWindow(object):
    def debug_init(self):

        cred = json.load(open("auth_success.json"))
        os.remove("auth_success.json")
        print("loaded in credentials")
        username, password = cred['user_name'], cred['password']

        print("Starting Handler")
        self.handler = SLMISHandler()
        self.handler.authentication(username, password)
        self.username = username
        # self.handler.authentication("gsulay", "{4_k66iI")

        
        all_sections_dict = self.handler.get_faculty_schedule()

        for section in all_sections_dict.keys():
            section = self.handler.view_cleaner(section)
            self.sections.addItem(section)
        self.label.setText(self.sections.item(1).text())
        self.handler.init_sections()
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1182, 922)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.sections = QtWidgets.QListWidget(parent=self.centralwidget)
        self.sections.setObjectName("sections")
        self.sections.itemClicked.connect(self.section_shift)

        self.horizontalLayout_2.addWidget(self.sections)
        self.mainFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.mainFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("sectionName")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.generateTemplateBttn = QtWidgets.QPushButton(parent=self.mainFrame)
        self.generateTemplateBttn.setObjectName("generateTemplateBttn")
        self.generateTemplateBttn.clicked.connect(self.generate_template)
        self.horizontalLayout.addWidget(self.generateTemplateBttn)

        self.loadGradeBttn = QtWidgets.QPushButton(parent=self.mainFrame)
        self.loadGradeBttn.setObjectName("loadGradeBttn")
        self.loadGradeBttn.clicked.connect(self.load_grades)
        self.horizontalLayout.addWidget(self.loadGradeBttn)

        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gradeView = QtWidgets.QTableView(parent=self.mainFrame)
        self.gradeView.setObjectName("gradeView")
        self.verticalLayout.addWidget(self.gradeView)
        self.gradeBttn = QtWidgets.QPushButton(parent=self.mainFrame)
        self.gradeBttn.setObjectName("gradeBttn")
        self.gradeBttn.setDisabled(True)
        self.gradeBttn.clicked.connect(self.grade)
        self.verticalLayout.addWidget(self.gradeBttn)
        self.progressBar = QtWidgets.QProgressBar(parent=self.mainFrame)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout_2.addWidget(self.mainFrame)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1182, 21))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(parent=self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.showMessage(f"Hello XU - Employee")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRelogin = QtGui.QAction(parent=MainWindow)
        self.actionRelogin.setObjectName("actionRelogin")
        self.menuSettings.addAction(self.actionRelogin)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Section"))
        self.generateTemplateBttn.setText(_translate("MainWindow", "Generate Template"))
        self.loadGradeBttn.setText(_translate("MainWindow", "Load Gradebook"))
        self.gradeBttn.setText(_translate("MainWindow", "Grade!"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionRelogin.setText(_translate("MainWindow", "Relogin"))
    
    def section_shift(self, x):
        item_no = self.sections.currentRow()
        self.label.setText(self.sections.item(item_no).text())
    
    def generate_template(self):
        self.statusbar.showMessage("Gathering data...")
        item_no = self.sections.currentRow()
        self.handler.generate_template(item_no)
        self.statusbar.showMessage("Done!")
    
    def load_grades(self):
        filter = FILE_FILTERS[0]
        filters = ";;".join(FILE_FILTERS)
        filename, selected_filter = QFileDialog.getOpenFileName(
                                                             filter=filters,
                                                             initialFilter=filter,
                                                             )
        if filename == "":
            return
        df = pd.read_excel(filename)
        self.df = df
        table_model = TableModel(df)
        self.gradeView.setModel(table_model)
        self.gradeBttn.setDisabled(False)
    
    def grade(self):
        self.handler.grade(self.df, self.sections.currentRow())
        self.statusbar.showMessage("Done!")
        button = QMessageBox.information(None, "Success", "Grading completed!")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()

    login_dialog = Ui_Dialog()
    if login_dialog.exec() == QDialog.DialogCode.Accepted:
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        QMessageBox.information(None, "Success", "Logged in successfully!\nOpening main window...")
        MainWindow.show()
        ui.debug_init()
    else:
        QMessageBox.warning(None, "Failure", "Login failed!")
    
    sys.exit(app.exec())



